title: Mehrdad Rafiee
author: Mehrdad Rafiee
description: > # this means to ignore newlines until "baseurl:"
  Howdy!
  I am a minimalist UI Engineer who helps an organization to Deliver Content on the Netwrok.
  I <3 open source and this page is brought to you by using best of them.

github_username:  mehrdadrafiee
twitter_username: mehrdad_rafiee

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%a, %b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
