title: Mehrdad Rafiee
author: Mehrdad Rafiee
email: rafiee[DOT]mehrdad[AT]gmail[DOT]com
description: > # this means to ignore newlines until "baseurl:"
  Howdy!
  I am a UI Engineer who creates Content to be Delivered on the Netwrok.
  Started this blog to share my experiences with others.
  I <3 open source and this page is brought to you by using best of them.

twitter_username: bepetese
github_username:  mehrdadrafiee

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%a, %b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
